### ISSUE TITLE
More thorough normalization of punctuation by TICCL-unk (hyphens, dots, etc.)

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/ticcltools#10]
OCR may well insert any of the available characters for a particular punctuation mark such as hyphens and dots, etc.

Guiding principle should be findability for the user. This also entails facility of entering one's query. 

This means we should strive to normalize all divergent punctuation marks for at least hyphens and dots to the common keyboard form, i.e. '-' and '.'.

Divergent forms need to be added to the *punct list, to later enable FoLiA-correct to actually match and replace these.

**Comment by kosloot** [comment]
This is now implemented as follows:
- All hyphen/dash symbols are mapped to a 'normal' keyboard hyphen '-'
- Multiple hyphens are mapped to a single.
- Some 'dot' like symbols, at this moment `•` and `·`, are mapped to a normal keyboard dot '.'
- Multiple dots are NOT converted to a single dot. As this might interfere with ... and  such.

The implementation uses the ICU [Transcriptor](http://userguide.icu-project.org/transforms/general/) interface.

**Comment by martinreynaert** [comment]
May I take it this means you have finished work on TICCL-unk for now?

So, I will test.

**Comment by kosloot** [comment]
assuming it is tested....
