### ISSUE TITLE
Ligature for 'fi' missing in TICCL-unk's filter

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/ticcltools#23]
Hi,

ﬁctional#2
ﬁctitious#2
ﬁddle_and#2
ﬁddle_combination#2

It seems one of the most common ligatures, i.e. ﬁ, is missing from the default list in TICCL-unk: from the usage:

		 default the following filter is used: 
æ >ae;Æ } [:Uppercase Letter:]* > AE;Æ > Ae;œ > oe;Œ } [:Uppercase Letter:]+ > OE;Œ > Oe;ĳ > ij;Ĳ > IJ;ﬂ > fl;ﬀ > ff;ﬃ > ffi;ﬄ > ffl;ﬅ > st;ß > ss;'~' > '*';'#' > '*';[ ] > '_';[[:Hyphen:][:Dash:]]+ > '-';[•·]  > '.'

**Comment by kosloot** [comment]
fixed in GIT. (and roled out on red/black)
