### ISSUE TITLE
More info on TICCL-LDcalc progress would be welcome

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/ticcltools#24]
Hi,

I am running TICCL-LDcalc (with an insufficiently cleaned and overly large background corpus and some quite unfelicitous parameter settings regarding word lengths, but this is all quite beside the point).

The only feedback I get on progress is this:

reynaert@red:~$ tail -f /reddata/PILOTS/MORSE/RUN3redBACKGROUNDANAHASH_ManualMerged/zzz/TICCL/RUN3redCC1.tsv.clean.MERGED.ldcalc.20180708.stdout
running on 62 threads.
TICCL-LDcalc: reading clean file: /reddata/PILOTS/MORSE/RUN3blackBACKGROUNDANAHASH/zzz/TICCL/RUN3blackCC1.tsv.clean.merged
TICCL-LDcalc: read 122311709 clean words with frequencies
TICCL-LDcalc: read 76273160 hash values
...........................................

This is rather unfortunate:
- I have no idea what each dot produced (very slowly in this case) represents
- I have no idea how many more dots I should expect

It would be nice if some more information could be output to *stdout on occasion.

Thank you!

**Comment by martinreynaert** [comment]
My current run makes better progress and I now see that 50K sth. has been processed:

reynaert@red:/reddata/PILOTS/MORSE/RUN4FRQ10$ tail -f /reddata/PILOTS/MORSE/RUN4FRQ10/RUN4FRQ10.tsv.clean.confuslist.INDEXER.LDCALC.stdout
running on 62 threads.
TICCL-LDcalc: reading clean file: /reddata/PILOTS/MORSE/RUN3blackBACKGROUNDANAHASH/zzz/TICCL/RUN3blackCC1.tsv.clean.merged
TICCL-LDcalc: read 15734802 clean words with frequencies
TICCL-LDcalc: read 11234955 hash values
..................................................
50000
..........

Are these in fact confusion values processed?

reynaert@red:/reddata/PILOTS/MORSE/RUN4FRQ10$ wc /reddata/PILOTS/MORSE/RUN4FRQ10/RUN4FRQ10.tsv.clean.confuslist.INDEXER.index
    108810     108810 4979196947 /reddata/PILOTS/MORSE/RUN4FRQ10/RUN4FRQ10.tsv.clean.confuslist.INDEXER.index

We have corpus word values for 108,810 confusion values. These can be counted from *index.

User feedback might then read:

TICCL-LDcalc: read 122311709 clean words with frequencies
TICCL-LDcalc: read 76273160 hash values
TICCL-LDcalc: 108810 character confusion values to be read. We indicate progress by printing a dot for every 1000 confusion values processed
...........................................

**Comment by martinreynaert** [comment]
OK, zo zat het dus wel degelijk. 

reynaert@red:/reddata/PILOTS/MORSE/RUN4FRQ10$ tail -f /reddata/PILOTS/MORSE/RUN4FRQ10/RUN4FRQ10.tsv.clean.confuslist.INDEXER.LDCALC.stdout
running on 62 threads.
TICCL-LDcalc: reading clean file: /reddata/PILOTS/MORSE/RUN3blackBACKGROUNDANAHASH/zzz/TICCL/RUN3blackCC1.tsv.clean.merged
TICCL-LDcalc: read 15734802 clean words with frequencies
TICCL-LDcalc: read 11234955 hash values
..................................................
50000
..................................................
100000
........
creating .short file: /reddata/PILOTS/MORSE/RUN4FRQ10/RUN4FRQ10.tsv.clean.confuslist.INDEXER.LDCALC.short.ldcalc

creating .ambi file: /reddata/PILOTS/MORSE/RUN4FRQ10/RUN4FRQ10.tsv.clean.confuslist.INDEXER.LDCALC.ldcalc.ambi

Ik stel voor dat we dit inbouwen.

**Comment by kosloot** [comment]
Klopt!
Wat er geteld wordt, zijn de regels in de index/indexNT file.
Elke . is 1000 regels. En na elke 50.000 regels een newline.
LDcalc telt de lengte van die file niet op voorhand. Dat zou eventueel wel kunnen, uiteraard. Tegen wat kosten....

**Comment by kosloot** [comment]
this is added now.
