### ISSUE TITLE
TICCL-anahash: no way to direct output

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/ticcltools#25]
This, for now, does not have a high priority. There are more pressing matters.

Nevertheless, most tools allow pne to direct the output to a specific output directory, possibly with a custom prefix.

TICCL-anahash does not. So It has just overwritten two files that I produced before and might have wanted to examine again... You can tell by the dates.

[1]+  Done                    nohup /exp/sloot/usr/local/bin//TICCL-anahash --alph /reddata/PILOTS/MORSE/Aspell/eng.aspell.dict.clip0.lc.chars --artifrq 1000000000 --ngrams --background /reddata/PILOTS/MORSE/CORP/MERGED/AMALGAMLEX.eng.wordfreqlist.UNK.clean.NoRankingNumbers.LessSigns.hash.NoHapaxes.LessTags.FRQ10.txt /reddata/PILOTS/MORSE/RUN3blackBACKGROUNDANAHASH/zzz/TICCL/RUN3blackCC1.tsv.clean
reynaert@red:/reddata/PILOTS/MORSE/RUN4FRQ10$ ls -l
total 4
-rw------- 1 reynaert reynaert 639 Jul  9 18:28 nohup.out
reynaert@red:/reddata/PILOTS/MORSE/RUN4FRQ10$ ls -l /reddata/PILOTS/MORSE/RUN3blackBACKGROUNDANAHASH/zzz/TICCL/RUN3blackCC1.tsv.clean*
-rw-r--r-- 1 reynaert reynaert  12634534 Jul  5 15:09 /reddata/PILOTS/MORSE/RUN3blackBACKGROUNDANAHASH/zzz/TICCL/RUN3blackCC1.tsv.clean
-rw-r--r-- 1 reynaert reynaert 375455000 Jul  9 18:28 /reddata/PILOTS/MORSE/RUN3blackBACKGROUNDANAHASH/zzz/TICCL/RUN3blackCC1.tsv.clean.anahash
-rw-r--r-- 1 reynaert reynaert   8099950 Jul  9 18:26 /reddata/PILOTS/MORSE/RUN3blackBACKGROUNDANAHASH/zzz/TICCL/RUN3blackCC1.tsv.clean.corpusfoci
-rw-r--r-- 1 reynaert reynaert  32070106 Jul  7 01:59 /reddata/PILOTS/MORSE/RUN3blackBACKGROUNDANAHASH/zzz/TICCL/RUN3blackCC1.tsv.clean.ldcalc
-rw-r--r-- 1 reynaert reynaert  34466657 Jul  7 01:59 /reddata/PILOTS/MORSE/RUN3blackBACKGROUNDANAHASH/zzz/TICCL/RUN3blackCC1.tsv.clean.ldcalc.ambi
-rw-r--r-- 1 reynaert reynaert   2272900 Jul  7 02:00 /reddata/PILOTS/MORSE/RUN3blackBACKGROUNDANAHASH/zzz/TICCL/RUN3blackCC1.tsv.clean.ldcalc.ranked
-rw-r--r-- 1 reynaert reynaert 305148443 Jul  9 18:28 /reddata/PILOTS/MORSE/RUN3blackBACKGROUNDANAHASH/zzz/TICCL/RUN3blackCC1.tsv.clean.merged
-rw-r--r-- 1 reynaert reynaert  19679397 Jul  7 01:59 /reddata/PILOTS/MORSE/RUN3blackBACKGROUNDANAHASH/zzz/TICCL/RUN3blackCC1.tsv.clean.short.ldcalc

**Comment by kosloot** [comment]
hmm, odd this never popped up before.
Shouldn't be too difficult to implement.

**Comment by kosloot** [comment]
Ok, I implemented an `-o` option to specify an output file.
This is in line with most of the other TICCL_* tools that know about `-o`

**Comment by martinreynaert** [comment]
It's a pity that it is not fully in line with the most commonly implemented versions of -o though.

Most versions append their own suffixes.

**Comment by martinreynaert** [comment]
To tell the truth, I would prefer them not to, really.

**Comment by kosloot** [comment]
OK: Adding default suffixes is rather easy.
Could add that today.

Removing all default in all programs is tricky:
- we use predefined suffixes to assure the right programs get the right data
- programs actively test for certain suffixes
- sometimes we produces several files with different suffixes. With default removed, we nee more options to specify all different files.
- the current scripts would therefore fail enormously 

So changing this is not to be taken lightheartedly!

**Comment by martinreynaert** [comment]
I agree, I already had misgivings about writing I would rather not have the modules adding suffixes.

The main thing to strive for would be to have all modules behave as far as possible in the same way.

Also, the user should be able to learn from the usage notifications what the output's file name(s) will be.

With regards to maintainability of scripts: it seems to me it would be easiest if one could repeat the very same filename prefix (with path, if so desired, but this might conflict with Nextflow??) for every module.

So: one would specify '-o /reddata/PILOTS/MORSE/RUN5/RUN5HathiTrustOCR'

and e.g. TICCL-unk would output: /reddata/PILOTS/MORSE/RUN5/RUN5HathiTrustOCR.clean after having received as input /reddata/PILOTS/MORSE/RUN5/RUN5HathiTrustOCR.tsv.

And TICCL-rank would receive  /reddata/PILOTS/MORSE/RUN5/RUN5HathiTrustOCR.index and output  /reddata/PILOTS/MORSE/RUN5/RUN5HathiTrustOCR.rank.

Thanks!

Please note: the current PICCL Nextflow script is already broken as we speak.

**Comment by kosloot** [comment]
Ok, this sounds like a PLAN™
I adapted TICCl-anahash now to assure a `.anahash` suffix is present.
I will create a separate issue to overhaul all modules to implement this (mostly this will already work) and to improve the usage() and man pages.

**Comment by proycon** [comment]
> With regards to maintainability of scripts: it seems to me it would be easiest if one could repeat the very same filename prefix (with path, if so desired, but this might conflict with Nextflow??) for every module.

As long as the output file has at least the same directory prefix as the input file (output may possibly be in subdirs) it should be okay, this is something to catch in the nextflow task.

> Please note: the current PICCL Nextflow script is already broken as we speak.

Do make sure to adapt it asap (as also discussed in LanguageMachines/PICCL#35). Ideally the ``master`` branch of PICCL should always be compatible with the ``master`` branch of ticcltools (this implies it will work in the LaMachine development, which is what Travis CI uses as well; so you have a good foundation for testing and further development).

**Comment by kosloot** [comment]
as of 18-02-2020 the master branch is fixed, I close this issue for now
