### ISSUE TITLE
Ranking feature #1: f2len_rank : subtract artifrq from frequencies >= artifrq

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/ticcltools#32]
As we have observed, when all Correction Candidates have the artifrq, ranking feature #1 : f2len cannot work.

I would like to have the option to have the artifrq subtracted from all CCs that have artifrq or higher, for ranking feature 1.

Note that we already have this option for application to all frequencies, in the 'usage':

	--artifrq 'arti'	 decrease frequencies with value 'arti'.
			 (which should match the artifreq used in TICCL-LDcalc)

In so far as this parameter may be confusing - in other modules this is used to actually set the artifrq - I suggest this be renamed to sth. like --subtractartifrqoverall. And to name the new option: 
--subtractartifrqfeature1 (unless you can think about sth. shorter). 

I take it that no default artifrq is set in TICCL-rank when the current --artifrq parameter is not specified?

**Comment by kosloot** [comment]
Well, --artifrq is a misnomer indeed.
But introducing 2 different options seems uncalled for.
the value of artifreq, or a new --subtractartifrq option, is only used for the frequencies of the CC's, (also freq2), so both options would have exactly the same effect!.

There might be a related issue, as TICCL-rank some times uses the 'reduced' frequency:
for feature2
and sometimes the original value: for sorting the output to create input for chaining.
This might be correct, but is worth to note....

**Comment by kosloot** [comment]
Ok, after some discussion, two options are implemented.
``--subtractartifrqfeature1`` and ``--subtractartifrqfeature2``

The old ``--artifrq`` is still in place and  involves --subtractartifrqfeature2
