### ISSUE TITLE
Character confusion values in TICCL-rank/chain/chainclean output

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/ticcltools#35]
In TICCLAT we are set to actively start making use of the anagram confusion value observed between word forms paired by TICCL.

Beyond TICCL-LDcalc this confusion value is currently output only to the TICCL-rank *debug file as shown in this example:

reynaert@black:/reddata/PILOTS/DIABOR/DIABORhemp2/zzz/TICCL$ grep '^diamantsaeger' .DIABORhemp2.clean.ldcalc.debug.ranked
diamantsaeger#1#1#Diamantzager#100000001#100000001#3538597833#9~1#100000001~1#2~1#11~1#1~1#1~1#1~1#0~2#22~1#0~N#100000000~N#2~1#0~1#0~1#13#0.518519

It is there output in the 7th column.

Checking in the character confusion file, we indeed see that this is the case:

reynaert@violet:/reddata/COMBI/Data$ cat /reddata/POLMASH/TRI/ALPH/nld.aspell.dict.clip20.ld2.charconfus |grep '3538597833'
3538597833#es~z

We would like TICCL-rank, TICCL-chain and TICCL-chainclean to also retain and output these values.

We have no specific wishes as to where this extra column is to be inserted in the output of these tools. Please locate it wherever you find it will least affect the other tools in the whole TICCL/PICCL pipelines.

**Comment by kosloot** [comment]
Ok, that is doable. But it will affect most tools anyhow. Files created with these 'newer' versions will NOT be usable with older versions. Not a big problem. I hope....
But files created by 'old' versions will also NOT be readable with the new versions. 
Or at least: being backward compatible is a lot of work, maybe. Must look into that....

**Comment by kosloot** [comment]
@martinreynaert I installed on violet versions of rank, chain and chainclean that adds extra columns. chain will still work on 'older' files, as does chainclean.

PLEASE TEST

**Comment by kosloot** [comment]
ok, this is in use for almost a year now. so it works
