### ISSUE TITLE
TICCL-anahash input: also simple word lists

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/ticcltools#36]
TICCL-anahash on the one hand does not use word frequencies, on the other hand it requires a word frequency list as its input. 

Especially in combination with the --list option, input would most often be a simple word list instead of a frequency list. We would much appreciate if this option would be enabled.

**Comment by kosloot** [comment]
Well, except for the `--list` option, TICCL-anahash DOES use the frequencies to compare against the `--artifrq' value.
So i can implement 'freqency-less' input for that case only.
OR:
we assume a frequency of 1, when absent. Which implies including them in the foci-list for instance.

**Comment by martinreynaert** [comment]
Ah, right, I indeed overlooked that aspect of TICCL-anahash. My apologies!

The second option has my preference, there may be occasions where we do want them to be included in the foci-list, indeed. 

Thank you!

**Comment by kosloot** [comment]
So, for both 'corpora' (The input AND the background) we accept simple word-lists and assign a default frequency of 1.
In GIT now. installed on violet.

**Comment by martinreynaert** [comment]
I have tested with just a word list for the --list option. This works as planned!
