### ISSUE TITLE
[possible regression?] TICCL-indexerNT produces empty output file

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/ticcltools#40]
As part of PICCL/ticcl.nf , TICCL-indexerNT (git master) is called as follows:

``TICCL-indexerNT --hash "corpus.wordfreqlist.tsv.clean.anahash" --charconf "eng.aspell.dict.c0.d2.confusion" --foci "corpus.wordfreqlist.tsv.clean.corpusfoci" -o "corpus.wordfreqlist.tsv.clean" -t 8 ``

It produces an **empty**  ``corpus.wordfreqlist.tsv.clean.indexNT``

Input files are attached:
[indexerntissue.tar.gz](https://github.com/LanguageMachines/ticcltools/files/4221470/indexerntissue.tar.gz)

**Comment by martinreynaert** [comment]
The attached corpusfoci file has 1 KB. It is empty. So no words are actually evaluated. There is sth. wrong in the prior modules' invocations, most likely.

**Comment by proycon** [comment]
Right, I hadn't spotted that yet. Well spotted. That must be it then. I'll see where that goes wrong and do a follow up with a new bug report then.
