### ISSUE TITLE
Removing common parts between variants and CC bi/trigrams is counter-productive

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/ticcltools#45]
We have at some point in the past decided to remove common parts between bi/trigram variants and CCs. This was meant to reduce the work load. It has proven to be counter-productive in that the bi/trigram CCs that remain cannot be in accord with the unigram best-first ranked candidate, leading to lots of False Positives.

In the C++ code we see, e.g. 

`	// remove all common parts at the end.
	parts1.pop_back();
	parts2.pop_back();`

and

`	// remove all common parts at the begin.
	parts1.erase(parts1.begin());
	parts2.erase(parts2.begin());`

Flagging out these commands (and similar ones, if present) may well solve the whole problem.

I think it is likely that we counted the cases per unigram remaining after the erasures towards a ranking feature. I think we should retain that, if present.

This will inevitably lead to longer output lists, but that is a price that needs paying.

I have in the past in other, much more elaborate issues, tried to pinpoint this problem in hopes of getting this solved. I will need to check which and notify you. They will likely be ripe for being closed.

Thank you!

**Comment by kosloot** [comment]
I tried to disable this code, but didn't see any effect in my small tests.
It is in Git now.

I hope this ends up in LaMachine-dev soon, (@proycon)  so you can test it on your examples.

**Comment by martinreynaert** [comment]
Thanks! Will test as soon as possible!

**Comment by proycon** [comment]
> I hope this ends up in LaMachine-dev soon, ***@***.***)  so you can test it on your examples.

Things are automatically in lamachine-dev if you're using the git master
branch (and automatically in the stable lamachine once released).
There's no need for action on my part there...

**Comment by kosloot** [comment]
assume @martinreynaert is satisfied with the solutiuon
